---

blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/XXXXXX  #add URL once discussion page is set up
    about: Ask questions and discuss with other community members
