---
name: Data submission template
description: Suggest a new dataset to be included in the living catalog
labels: [New dataset, to be added]

body:
  - type: checkboxes
    attributes:
      label: Duplicate checks
      options:
        - label: >
            I have checked that the dataset is not yet included in the catalog.
          required: true
  - type: dropdown
    id: catalog
    attributes:
      description: Please specify the overarching catalog that the data belong to
      label: Catalog
      options:
        - hazard
        - exposure-vulnerability
        - response
    validations:
      required: true
  - type: textarea
    id: further-details
    attributes:
      description: >
        Please provide any further details relevant for this new data entry
      label: Further details
    validations:
      required: true
