name: Data submission form (hazard data)
description: Suggest a new hazard dataset to be included in the living catalog
labels:
- Hazard
- Enhancement
body:
- type: dropdown
  id: catalog
  attributes:
    label: Catalog
    description: Overarching catalog that the data belong to (i.e. hazard, exposure-vulnerability)
    options:
    - hazard
  validations:
    required: true
- type: dropdown
  id: risk_data_type
  attributes:
    label: Risk data type
    description: Risk driver (i.e. hazard, exposure, vulnerability, response)
    options:
    - hazard
  validations:
    required: true
- type: dropdown
  id: category
  attributes:
    label: Category
    description: Category of data type according to classification scheme (see readme)
    options:
    - flood
    - precipitation-related
    - temperature-related
    - wind-related
    - environmental
    - multi-hazard
  validations:
    required: true
- type: dropdown
  id: subcategory
  attributes:
    label: Subcategory
    description: Subcategory of data type according to classification scheme (see
      readme)
    options:
    - flash flood
    - not specified
    - landslide
    - drought
    - tropical cyclone
    - coldwave
    - windstorm
    - urban flood
    - wildfire
    - extratropical cyclone
    - tornado
    - multi-hazard
    - heatwave
    - pluvial flood
    - river flood
    - coastal flood
  validations:
    required: true
- type: input
  id: title_collection
  attributes:
    label: Collection title
    description: Name of the dataset collection; the collection title must be the
      same for each item belonging to that collection (see 'Item title' for further
      instructions).
    placeholder: e.g. CMIP6 heat stress indicators
  validations:
    required: true
- type: input
  id: title_collection_short
  attributes:
    label: Short collection title
    description: Short name/acronym of the dataset (if available)
    placeholder: e.g. CMIP6-HIS
- type: textarea
  id: description_collection
  attributes:
    label: Collection description
    description: Detailed description of the dataset collection; the collection description
      must be the same for each item belonging to that collection
    placeholder: e.g. The indices are provided for historical and future climate projections
      (SSP1-2.6, SSP2-4.5, SSP3-7.0, SSP5-8.5) included in the Coupled Model Intercomparison
      Project Phase 6 (CMIP6) and used in the 6th Assessment Report of the Intergovernmental
      Panel on Climate Change (IPCC).
  validations:
    required: true
- type: input
  id: title_item
  attributes:
    label: Item title
    description: Concise name of the dataset item; each item from the same collection
      needs to have a unique name. If data are from the same overall data source,
      but metadata attributes differ, these are separate items that belong to the
      same collection. Please submit separate data items per collection by creating
      a new issue.
    placeholder: e.g. CMIP6 heat stress indicators for historical period (1850-2014)
  validations:
    required: true
- type: textarea
  id: description_item
  attributes:
    label: Item description
    description: Detailed description of the dataset item; if there is only one item
      in the collection, the collection description can be copied here.
    placeholder: e.g. Heat index is a heat stress indicator used by the US National
      Oceanic and Atmospheric Administration (NOAA) National Weather Service for issuing
      heat warnings. It is calculated using multiple linear regression based on daily
      maximum temperature and relative humidity (calculated from daily mean specific
      humidity and surface pressure).
  validations:
    required: true
- type: dropdown
  id: spatial_scale
  attributes:
    label: Spatial scale
    description: Spatial coverage of the dataset
    options:
    - (near-)global
    - regional
    - national
    - subnational
  validations:
    required: true
- type: input
  id: bbox
  attributes:
    label: Bounding box
    description: Bounding box of the dataset in the format [west, south, east, north]
    placeholder: e.g. [-180, -90, 180, 90]
  validations:
    required: true
- type: dropdown
  id: reference_period
  attributes:
    label: Reference period
    description: Reference period for which the data are available
    options:
    - historical
    - future
    - historical & future
  validations:
    required: true
- type: input
  id: temporal_coverage
  attributes:
    label: Temporal coverage
    description: Temporal coverage of the dataset format YYYY, YYYY-YYYY or YYYY-now
      (if data are updated in real time)
    placeholder: e.g. 1850-2014
  validations:
    required: true
- type: input
  id: temporal_resolution
  attributes:
    label: Temporal resolution
    description: Temporal resolution of the dataset
    placeholder: e.g. hourly, monthly, yearly, x-hourly, etc.
- type: dropdown
  id: scenario
  attributes:
    label: Scenario
    description: Name of the scenarios used if 'Reference period' is 'future'
    options:
    - RCPs
    - SSP-RCP combinations
    - warming levels
    - extrapolation
    - other (please specify below)
- type: input
  id: custom_scenario
  attributes:
    label: Custom scenario
    description: Name of the custom scenario used if 'Scenario' is 'other'
