---
name: Data submission template (Hazard)
description: Suggest a new hazard dataset to be included in the living catalog
labels: [New dataset, Hazard]

body:
  - type: checkboxes
    attributes:
      label: Duplicate checks
      options:
        - label: >
            I have checked that the dataset is not yet included in the catalog.
          required: true

  - type: dropdown
    id: catalog
    attributes:
      description: Overarching catalog that the data belong to (i.e. hazard, exposure-vulnerability)
      label: Catalog
      options:
        - hazard
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      description: Category of data type according to hierarchical structure (see readme)
      label: Category
      options:
        - flood
        - precipitation-related
        - temperature-related
        - wind-related
        - environmental
        - multi-hazard
    validations:
      required: true

  - type: dropdown
    id: subcategory
    attributes:
      description: Subcategory of data type according to hierarchical structure (see readme)
      label: Subcategory
      options:
        - coastal flood
        - fluvial flood
        - pluvial flood
        - flood type not specified
        - drought
        - snowstorm/blizzard
        - heat wave
        - cold wave
        - tropical cyclone
        - extratropical cyclone
        - wildfire
        - multi hazard
    validations:
      required: true

  - type: dropdown
    id: risk-data-type
    attributes:
      description: Risk driver (i.e. hazard, exposure, vulnerability, response)
      label: Risk data type
      options:
        - hazard
    validations:
      required: true

  - type: input
    id: title-collection
    attributes:
      description: Name of the dataset collection; the collection name must be the same for each item belong to that collection (see 'Title (item)' for further instructions).
      label: Title (collection)
    validations:
      required: true

  - type: input
    id: title-short
    attributes:
      description: (optional) short name/acronym of dataset
      label: Title short
  - type: textarea
    id: description-collection
    attributes:
      description: Detailed description of the dataset collection
      label: Description of dataset collection
    validations:
      required: true

  - type: input
    id: title-item
    attributes:
      description: Concise name of the dataset item; each item from the same collection needs to have a unique name. If data are from the same overall data source, but metadata attributes differ, these are separate items that belong to the same collection. Please submit separate data items per collection by creating a new issue.
      label: Title (item)
      placeholder: TEST
      value: TEST TEST
    validations:
      required: true

  - type: textarea
    id: description-item
    attributes:
      description: Detailed description of the dataset item; if there is only one item in the collection, the collection description can be copied here.
      label: Description of dataset item
    validations:
      required: true

  - type: dropdown
    id: spatial_scale
    attributes:
      label: Spatial scale
      options:
        - (near-)global
        - regional
        - national
        - subnational
    validations:
      required: true

  - type: input
    id: bbox
    attributes:
      description: Bounding box (i.e. spatial extent) of the dataset given in WGS84 coordinates (xmin, ymin, xmax, ymax)
      label: Bounding box
      placeholder: ex. -180, -90, 180, 90
    validations:
      required: true

  - type: dropdown
    id: data-type
    attributes:
      label: Data type
      options:
        - raster
        - vector
        - tabular
    validations:
      required: true

  - type: dropdown
    id: format
    attributes:
      label: Data format
      options:
        - geotiff
        - netcdf
        - geopackage
        - shapefile
        - geodatabase
        - FlatGeobuf
        - GeoParquet
        - GRIB
        - GRIB2
        - csv
        - excel
        - ascii
        - txt
        - pbf
        - other (please specify next)
    validations:
      required: true

  - type: input
    id: custom-data-format
    attributes:
      label: New data format (if 'other' selected)
      description: If you selected 'other', please specify the data format here
      placeholder: Enter new data format

  - type: input
    id: coordinate-system
    attributes:
      label: Coordinate system
      description: Numerical code of the coordinate reference system (CRS)
      placeholder: ex. 4326; 54009
    validations:
      required: true

  - type: input
    id: spatial-resolution
    attributes:
      label: Spatial resolution
      description: Spatial resolution in numeric value or use "administrative unit", "feature level", "event"
      placeholder: "30"
    validations:
      required: true

  - type: dropdown
    id: spatial-resolution-unit
    attributes:
      label: (optional) spatial resolution unit if numeric
      options:
        - raster
        - vector
        - tabular
    validations:
      required: true

  - type: textarea
    id: further-details
    attributes:
      description: >
        Please provide any further details relevant for this new data entry
      label: Further details
    validations:
      required: true

