---
name: Error Report
description: Report error (e.g. faulty link, wrong metadata) in the living catalog.
labels: [Error, Needs refinement]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Version checks
      options:
        - label: I have checked that this issue has not already been reported.
          required: true
        - label: I have checked that this error exists on the latest version of the living catalog on `main` [here](https://github.com//climate-risk-data/climate-risk-stac).
          required: true
  
  - type: dropdown
    id: kind
    attributes:
      description: What kind of error is this?
      label: Kind of error
      options:
        - Page is not displayed
        - Link to external content is faulty
        - Metadata attribute(s) are wrong
        - I found a duplicate
        - other (please specify in 'Additional context')
    validations:
      required: true

  - type: input
    id: location
    attributes:
      description: >
        Please provide the URL of the error in question
      label: Location of the error
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      description: >
        Please provide any additional context and a suggested fix if possible (i.e. correct link or metadata attributes). If metadata attributes need updating, please consider doing so directly in the respective CSV file [here](https://github.com/XXXXXX).
      label: Additional context
    validations:
      required: true